export const GET_FORMS = "GET_FORMS";
export const GET_FORM = "GET_FORM";
export const UPDATE_FORM = "UPDATE_FORM";
export const POST_FORM = "POST_FORM";
export const FORM_ERROR = "FORM_ERROR";
export const DELETE_FORM = "DELETE_FORM";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";

export const ADD_APPLICATION_SUCCESS = "ADD_APPLICATION_SUCCESS";
export const ADD_APPLICATION_REQUEST = "ADD_APPLICATION_REQUEST";
export const ADD_APPLICATION_FAIL = "ADD_APPLICATION_FAIL";
export const GET_USER_APPLICATIONS_SUCCESS = "GET_USER_APPLICATIONS_SUCCESS";
export const GET_USER_APPLICATIONS_FAIL = "GET_USER_APPLICATIONS_FAIL";

export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const GET_HR_PROFILE_SUCCESS = "GET_HR_PROFILE_SUCCESS";
export const GET_HR_PROFILE_FAIL = "GET_HR_PROFILE_FAIL";
export const UPDATE_HR_PROFILE_REQUEST = "UPDATE_HR_PROFILE_REQUEST";
export const UPDATE_HR_PROFILE_SUCCESS = "UPDATE_HR_PROFILE_SUCCESS";
export const UPDATE_HR_PROFILE_FAIL = "UPDATE_HR_PROFILE_FAIL";

export const GET_ALL_APPLICATIONS_REQUEST = "GET_ALL_APPLICATIONS_REQUEST";
export const GET_ALL_APPLICATIONS_FAIL = "GET_ALL_APPLICATIONS_FAIL";
export const GET_ALL_APPLICATIONS_SUCCESS = "GET_ALL_APPLICATIONS_SUCCESS";
export const GET_APPLICATION_SUCCESS = "GET_APPLICATION_SUCCESS";
export const GET_APPLICATION_FAIL = "GET_APPLICATION_FAIL";
export const DELETE_USER_APPLIED_APPLICATION =
  "DELETE_USER_APPLIED_APPLICATION";

export const GET_APPLIED_USERS = "GET_APPLIED_USERS";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const ADD_EXPERIENCE_REQUEST = "ADD_EXPERIENCE_REQUEST";
export const ADD_EXPERIENCE_FAIL = "ADD_EXPERIENCE_FAIL";
export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";

export const ADD_EDUCATION_REQUEST = "ADD_EDUCATION_REQUEST";
export const ADD_EDUCATION_FAIL = "ADD_EDUCATION_FAIL";
export const ADD_EDUCATION_SUCCESS = "ADD_EDUCATION_SUCCESS";
export const DELETE_EDUCATION = "DELETE_EDUCATION";

export const GET_HRS_SUCCESS = "GET_HRS_SUCCESS";
export const GET_PENDING_HRS_SUCCESS = "GET_PENDING_HRS_SUCCESS";

export const GET_HRS_FAIL = "GET_HRS_FAIL";

export const ADD_HR_SUCCESS = "ADD_HR_SUCCESS";
export const ADD_HR_FAIL = "ADD_HR_FAIL";
export const HR_VERIFY_REQUEST = "HR_VERIFY_REQUEST";

export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAIL = "SEND_OTP_FAIL";
export const VERIFY_REQUEST_SUCCESSFUL = "VERIFY_REQUEST_SUCCESSFUL";

export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";

export const UPDATE_APPLICATION_RESULT_SUCCESS =
  "UPDATE_APPLICATION_RESULT_SUCCESS";
export const UPDATE_APPLICATION_RESULT_FAIL = "UPDATE_APPLICATION_RESULT_FAIL";

export const SEND_ADMIN_SUCCESS = "SEND_ADMIN_SUCCESS";
export const SEND_ADMIN_FAIL = "SEND_ADMIN_FAIL";

export const GET_NOT_SUCCESS = "GET_NOT_SUCCESS";
export const GET_NOT_FAIL = "GET_NOT_FAIL";
